services:
  backend:
    container_name: backend
    build:
      context: ./gestao_de_pontos
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-coakid779t8c73ek3q70-a.oregon-postgres.render.com:5432/gestaodepontosdb_qvsb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=XSbL4GYYfo5STi7LGl3HNWeKFMZnX86b
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: database
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=XSbL4GYYfo5STi7LGl3HNWeKFMZnX86b
      - POSTGRESQL_DATABASE=gestaodepontosdb_qvsb
    volumes:
      - database-data:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database-data: